name = "KitePowerAnalysis"
uuid = "2e862f93-59fe-4587-8c1d-50677f0ebc8b"
authors = ["Martin Kosch <martin.kosch@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
